### ISSUE TITLE
You do not have permission to redistribute JSON For mIRC

### ISSUE THREAD

**Issue by SReject** [Heep123/LinkSafety#1]
In [script.ini](https://github.com/Heep123/LinkSafety/blob/d5623863f0a3b43407d6c828dce0d52aa7b172ec/script.ini you include a copy of [JSON for mIRC](https://github.com/SReject/JSON-For-Mirc/tree/v0.2.4) of which stipulates in the [notes section](https://github.com/SReject/JSON-For-Mirc/tree/v0.2.4#notes--) that it is not to be redistributed. Instead remove the file and link to its [Release Page](https://github.com/SReject/JSON-For-Mirc/releases/tag/v0.2.41-beta) for users of your script(s) to download.

**Comment by Heep123** [comment]
I appear to recall getting it from somewhere other than that repository, but I'll remove it. This project is outdated now anyway.
